### ISSUE TITLE
Core driving integration

### ISSUE THREAD

**Issue by eliabieri** [eliabieri/hackzurich_2022#1]
Make RC car controllable from the Raspberry Pi (preferably through Python)

**Comment by Nando5011** [comment]
`
try:
    import RPi.GPIO as GPIO
except RuntimeError:
    print("Error importing RPi.GPIO!  This is probably because you need superuser privileges.  You can achieve this by using 'sudo' to run your script")

import time
import math

MOTOR_CONTROL_PIN = 13
STEERING_CONTROL_PIN = 12
PWM_FREQUENCY = 10000

PWM_MAX_DC = 100
PWM_75_DC = 75
PWM_NOM_DC = 50
PWM_MIN_DC = 0

#Use BOARD numbering for pin numbers
GPIO.setmode(GPIO.BOARD)

#Initialzie GPIOs
GPIO.setup(MOTOR_CONTROL_PIN, GPIO.OUT, initial=GPIO.LOW)
GPIO.setup(STEERING_CONTROL_PIN, GPIO.OUT, initial=GPIO.LOW)

#Initalize as PWM, set DC to 0 and stop
motorControl = GPIO.PWM(MOTOR_CONTROL_PIN, PWM_FREQUENCY)
motorControl.changeDutyCycle(0)
steeringControl = GPIO.PWM(STEERING_CONTROL_PIN, PWM_FREQUENCY)
steeringControl.changeDutyCycle(0)

motorControl.start()
steeringControl.start()

while 1:
    for i in range(6):
        #Increment Duty Cycle by 20% every pass
        motorControl.ChangeFrequency(i*51)

        steeringAngleOffset = (i/5)*(2*math.pi)
        #Steering angle offset somewhere between +/-25% DC value
        steeringAngleOffset = math.sin(steeringAngleOffset)*(25)
        #DC value between 50% and 100%
        steeringControl.ChangeFrequency(PWM_75_DC+steeringAngleOffset)

        print("Step " + (i+1) + "/6, ")
        print("motorPin = " + (i*51) + " (" + (100*(i*51)/PWM_MAX_DC) + "%), ")
        print("steeringPin = " + (PWM_75_DC+steeringAngleOffset) + " (" + (100*(PWM_75_DC+steeringAngleOffset)/PWM_MAX_DC) + "%)\n")

        time.sleep(3)

GPIO.cleanup()

`
